- id: outside_lights_turnon
  alias: outside_lights_turnon
  trigger:
  - event: sunset
    offset: -00:10:00
    platform: sun
  action:
  - entity_id: scene.eveninglightturnon
    service: scene.turn_on
- id: outside_lights_turnoff
  alias: outside_lights_turnoff
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: homeassistant.turn_off
    entity_id: light.outside_lights_1_level
- id: '1542741604798'
  alias: CarPresenceDrew
  trigger:
  - entity_id: binary_sensor.carpresencedrew
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.power_switch_1
    state: 'off'
  action:
  - data:
      entity_id: switch.power_switch_1
    service: switch.turn_on
- id: '1542741976924'
  alias: CarPresenceDrew_Off
  trigger:
  - entity_id: binary_sensor.carpresencedrew
    for:
      minutes: 1
      seconds: 15
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.power_switch_1
    state: 'on'
  action:
  - data:
      entity_id: switch.power_switch_1
    service: switch.turn_off
- id: '1545151196586'
  alias: Basement Christmas Lights Turn On
  trigger:
    platform: time
    at: '16:50:00'
  action:
  - entity_id: scene.christmas_lights_on
    service: scene.turn_on
- id: '154515119658898'
  alias: Basement Christmas Lights Turn Off
  trigger:
  - at: '23:00:00'
    platform: time
  action:
  - entity_id: scene.christmas_lights_off
    service: scene.turn_on
- id: '1546968675789'
  alias: turn on front porch lights for activity
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.outside_fd_lights
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.outside_fd_lights
    service: switch.turn_on
- id: '1547008207879'
  alias: turn off front porch lights for motion
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    for: '120'
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.outside_fd_lights
    state: 'on'
  action:
  - data:
      entity_id: switch.outside_fd_lights
    service: switch.turn_off
