- id: outside_lights_turnon
  alias: outside_lights_turnon
  trigger:
  - event: sunset
    offset: -00:10:00
    platform: sun
  action:
  - entity_id: scene.eveninglightturnon
    service: scene.turn_on
- id: outside_lights_turnoff
  alias: outside_lights_turnoff
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: homeassistant.turn_off
    entity_id: light.outside_lights_1_level
- id: '1542741604798'
  alias: CarPresenceDrew
  trigger:
  - entity_id: binary_sensor.carpresencedrew
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: cover.garagedoorcontrol
    state: closed
  action:
  - data:
      entity_id: cover.garagedoorcontrol
    service: cover.open_cover
- id: '1542741976924'
  alias: CarPresenceDrew_Off
  trigger:
  - entity_id: binary_sensor.carpresencedrew
    for:
      minutes: 1
      seconds: 15
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: cover.garagedoorcontrol
    state: open
  action:
  - data:
      entity_id: cover.garagedoorcontrol
    service: cover.close_cover
- id: '1545151196586'
  alias: Basement Christmas Lights Turn On
  trigger:
    platform: time
    at: '16:50:00'
  action:
  - entity_id: scene.christmas_lights_on
    service: scene.turn_on
- id: '154515119658898'
  alias: Basement Christmas Lights Turn Off
  trigger:
  - at: '23:00:00'
    platform: time
  action:
  - entity_id: scene.christmas_lights_off
    service: scene.turn_on
- id: '1546968675789'
  alias: turn on front porch lights for activity
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.outside_fd_lights
    state: 'off'
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.outside_fd_lights
    service: switch.turn_on
- id: '1547008207879'
  alias: turn off front porch lights for motion
  trigger:
  - entity_id: binary_sensor.ring_front_door_motion
    for: '120'
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.outside_fd_lights
    state: 'on'
  action:
  - data:
      entity_id: switch.outside_fd_lights
    service: switch.turn_off
- id: '1547038329695'
  alias: turn on front door lights with front door open
  trigger:
  - entity_id: sensor.front_door
    from: Closed
    platform: state
    to: Open
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  - condition: state
    entity_id: switch.outside_fd_lights
    state: 'off'
  action:
  - data:
      entity_id: switch.outside_fd_lights
    service: switch.turn_on
- id: '1560310950577'
  alias: RocketClock - Daylight Morning
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.rocketclock_nightlight_2
    service: switch.turn_off
  - data:
      entity_id: switch.rocketclock_daylight_2
    service: switch.turn_on
- id: '1560310950578'
  alias: RocketClock - LightsOff
  trigger:
  - at: 09:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.rocketclock_daylight_2
    service: switch.turn_off
  - data:
      entity_id: switch.rocketclock_nightlight_2
    service: switch.turn_off
- id: '1560311397990'
  alias: RocketClock - Nighttime Evening
  trigger:
  - at: '18:45'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.rocketclock_nightlight_2
    service: switch.turn_on
  - data:
      entity_id: switch.rocketclock_daylight_2
    service: switch.turn_off
- id: '1574043468949'
  alias: TurnChristmasOn
  trigger:
  - at: 06:45
    platform: time
  - at: '17:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.christmastree1lights
    state: 'off'
  action:
  - data:
      entity_id: switch.christmastree1lights
    service: switch.turn_on
- id: '1574043842266'
  alias: TurnChristmasOff
  trigger:
  - at: 07:45
    platform: time
  - at: '22:45'
    platform: time
  condition:
  - condition: state
    entity_id: switch.christmastree1lights
    state: 'on'
  action:
  - data:
      entity_id: switch.christmastree1lights
    service: switch.turn_off
